빌드시 오류 해결
FirebaseError: Firebase: Need to provide options, when not being deployed to hosting via source. (app/no-options).
이러한 오류가 떠서 getAuth()를 firebase.ts에서 생성해서 export하는 식으로 해결